//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBank.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Cards = new HashSet<Card>();
            this.SignedServices = new HashSet<SignedService>();
            this.ServiceParameters = new HashSet<ServiceParameter>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Number { get; set; }
        public System.DateTime OpenDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public decimal Balance { get; set; }
        public decimal MinBalance { get; set; }
        public int Currency { get; set; }
        public bool IsOpened { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<SignedService> SignedServices { get; set; }
        public virtual ICollection<ServiceParameter> ServiceParameters { get; set; }
    }
}
