//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBank.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locality
    {
        public Locality()
        {
            this.Services = new HashSet<Service>();
            this.ServiceCategories = new HashSet<ServiceCategory>();
        }
    
        public int Id { get; set; }
        public int LocalityType { get; set; }
        public int LocalityId { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<ServiceCategory> ServiceCategories { get; set; }
    }
}
