//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBank.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Operations = new HashSet<Operation>();
            this.ServiceParameters = new HashSet<ServiceParameter>();
            this.SignedServices = new HashSet<SignedService>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string BankDetails { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public Nullable<int> LocalityId { get; set; }
        public string ScriptName { get; set; }
        public string TemplateName { get; set; }
    
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ICollection<ServiceParameter> ServiceParameters { get; set; }
        public virtual Locality Locality { get; set; }
        public virtual ICollection<SignedService> SignedServices { get; set; }
    }
}
