//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBank.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.IsBlocked = false;
            this.LoginAttempts = 0;
            this.IsActivated = false;
            this.IsAdmin = false;
            this.Accounts = new HashSet<Account>();
            this.SessionPasswords = new HashSet<SessionPassword>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FIO { get; set; }
        public string PassportNumber { get; set; }
        public string PassportData { get; set; }
        public bool IsBlocked { get; set; }
        public int LoginAttempts { get; set; }
        public bool IsActivated { get; set; }
        public bool IsAdmin { get; set; }
        public int CityId { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<SessionPassword> SessionPasswords { get; set; }
    }
}
